"""Tests for model fitting and multicollinearity diagnostics."""

from __future__ import annotations

import numpy as np
import pandas as pd
import pytest

from portfolio_profitability import modeling
from portfolio_profitability.config import RANDOM_STATE, TEST_SIZE, VIF_THRESHOLD


def test_split_proportions_and_disjointness(design):
    matrix, target = design
    train_x, test_x, train_y, test_y = modeling.split_data(matrix, target)

    assert len(train_x) + len(test_x) == len(matrix)
    assert len(test_x) == pytest.approx(len(matrix) * TEST_SIZE, abs=1)
    assert set(train_x.index).isdisjoint(set(test_x.index))
    assert train_x.index.equals(train_y.index)
    assert test_x.index.equals(test_y.index)


def test_split_is_reproducible_across_calls(design):
    matrix, target = design
    first = modeling.split_data(matrix, target, random_state=RANDOM_STATE)
    second = modeling.split_data(matrix, target, random_state=RANDOM_STATE)
    assert list(first[1].index) == list(second[1].index)


def test_a_different_seed_produces_a_different_split(design):
    matrix, target = design
    seeded = modeling.split_data(matrix, target, random_state=RANDOM_STATE)
    other = modeling.split_data(matrix, target, random_state=RANDOM_STATE + 1)
    assert list(seeded[1].index) != list(other[1].index)


def test_model_recovers_a_known_linear_relationship():
    # A regression fitted to data generated by an exact linear rule must
    # recover that rule, which proves the fitting path itself is sound.
    rng = np.random.default_rng(0)
    features = pd.DataFrame(
        {"a": rng.normal(size=400), "b": rng.normal(size=400)}
    )
    target = pd.Series(3.0 + 2.5 * features["a"] - 1.25 * features["b"])

    model = modeling.fit_linear_regression(features, target)

    assert model.intercept_ == pytest.approx(3.0)
    assert model.coef_[0] == pytest.approx(2.5)
    assert model.coef_[1] == pytest.approx(-1.25)


def test_coefficient_table_is_complete_and_sorted(design):
    matrix, target = design
    train_x, _, train_y, _ = modeling.split_data(matrix, target)
    model = modeling.fit_linear_regression(train_x, train_y)
    table = modeling.coefficient_table(model, matrix.columns)

    assert set(table["variable"]) == set(matrix.columns)
    assert len(table) == matrix.shape[1]
    assert table["coefficient"].is_monotonic_decreasing


def test_category_effects_strip_the_dummy_prefix(design):
    matrix, target = design
    train_x, _, train_y, _ = modeling.split_data(matrix, target)
    model = modeling.fit_linear_regression(train_x, train_y)
    effects = modeling.category_effects(modeling.coefficient_table(model, matrix.columns))

    assert list(effects.columns) == ["category", "coefficient"]
    assert len(effects) > 0
    assert not effects["category"].str.startswith("cat_").any()


def test_statsmodels_point_estimates_match_scikit_learn(design):
    matrix, target = design
    train_x, _, train_y, _ = modeling.split_data(matrix, target)

    sklearn_model = modeling.fit_linear_regression(train_x, train_y)
    ols = modeling.fit_ols_summary(train_x, train_y)

    assert ols.params["const"] == pytest.approx(sklearn_model.intercept_, rel=1e-6)
    for position, column in enumerate(train_x.columns):
        assert ols.params[column] == pytest.approx(
            sklearn_model.coef_[position], rel=1e-6
        )
    assert set(ols.pvalues.index) == {"const", *train_x.columns}


def test_vif_excludes_the_constant_and_covers_every_variable(design):
    matrix, _ = design
    vif = modeling.variance_inflation_factors(matrix)

    assert set(vif["variable"]) == set(matrix.columns)
    assert "const" not in set(vif["variable"])
    assert (vif["vif"] > 0).all()


def test_vif_detects_a_deliberately_collinear_column():
    rng = np.random.default_rng(1)
    base = rng.normal(size=300)
    frame = pd.DataFrame(
        {
            "a": base,
            "b": base * 2.0 + rng.normal(scale=0.001, size=300),
            "c": rng.normal(size=300),
        }
    )
    vif = modeling.variance_inflation_factors(frame)
    lookup = dict(zip(vif["variable"], vif["vif"]))

    assert lookup["a"] > VIF_THRESHOLD
    assert lookup["b"] > VIF_THRESHOLD
    assert lookup["c"] < VIF_THRESHOLD
